config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :sessions, :only => [:new, :create, :destroy] #only need 3 restful routes for sessions
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'
  get '/profile/:id' => 'users#show'
  post '/signup' => 'users#create'
  post '/signin' => 'sessions#create'
  get '/wall' => 'messages#index'
  post '/messages' => 'messages#create'
  post '/comments' => 'comments#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :message
  validates :content, :user_id, :message_id, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :content, :user_id,	presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :messages, dependent: :destroy
	has_many :comments, through: :messages
	#this allows my form to contain a password field and use it on the model side, even though there is no field
	#in my database called password (we used encrypted_password)
	attr_accessor :password, :password_confirmation

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
	validates :first_name,    :presence   => true,
              :length               => { :maximum => 30 }
  
	validates :last_name,    :presence   => true,
	          :length               => { :maximum => 30 }
  
	validates :email,   :presence   => true,
	          :format               => { :with => email_regex },
	          :uniqueness           => { :case_sensitive => false }
	          #this validates the form input
	validates :password,  :presence => true,
	          :confirmation         => true,
	          :length               => { :within => 4..100 }

	#before the user gets added to DB, run this function.
	before_save :encrypt_password

	#this method encrypts the user's unencrypted login attempt and returns true if the password is a match
	def has_password?(submitted_password)
		self.encrypted_password == encrypt(submitted_password)
	end

	# class method that checks whether the user's email and submitted password are valid
	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		if user.has_password?(submitted_password) == false
			return false
		elsif user.has_password?(submitted_password)
			return user
		end
	end

	def full_name
		self.first_name + " " + self.last_name
	end

	private
		def encrypt_password
			# generate a unique salt if it's a new user
			# self.password uses the attr_accessor we defined above to allow me to grab the inputed password
			self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{self.password}") if self.new_record?

			# encrypt the password and store that in the encrypted_password field
			self.encrypted_password = encrypt(self.password) #this self.password is what's in the post data!
		end

		# encrypt the password using both the salt and the passed password
		def encrypt(pass)
			Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
	end

	def new
	end

	def create
		@comment = Comment.new(comment_params)
		if @comment.save
			flash[:notice] = 'New comment created!'
			redirect_to '/wall', notice: 'Comment was successfully created.'
		else
			flash[:errors] = @comment.errors.full_messages
			redirect_to '/wall'
		end
	end
	private
		def comment_params
			params.require(:comment).permit(:user_id, :message_id, :content)
		end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  	@message = Message.new
  	@comment = Comment.new
  	@user = User.find(session[:user_id])
  	# @messages = User.select('messages.id, messages.content, messages.updated_at, messages.user_id, users.first_name, users.last_name').joins(:messages)
  	@messages = Message.select('messages.*, users.first_name, users.last_name').joins(:user).reverse_order
  end

  def new

  end

  def create
  	@message = Message.new(message_params)
  	if @message.save
  		flash[:notice] = 'New message created!'
  		redirect_to '/wall', notice: 'Message was successfully created.'
  	else
  		flash[:errors] = @message.errors.full_messages
  		redirect_to '/wall'
  	end
  end
	private
		def message_params
			params.require(:message).permit(:user_id, :content)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #bring up a form for a new session aka login form
  def new
  end

  #create the session resource ie, let user log in
  def create
  	#this references the function we made in user.rb
  	user = User.authenticate(params[:session][:email], params[:session][:password])
  	if user.nil?
      flash[:error] = "Email was not found."
      redirect_to new_session_path
    elsif user == false
      flash[:error] = "password was incorrect"
  	  #if there is an error, redirect back to login
  		redirect_to new_session_path
  	else
  		sign_in user #helper function
  		redirect_to '/wall'
  	end
  end

  def destroy
  	sign_out #helper function
  	redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
    if session[:user_id]
      redirect_to '/wall'
    end
    @messages = Message.all
  end

  def new
  	@user = User.new
  end

  def create #restful route to make new user!
  	@user = User.new(user_params)
  	if @user.save
  		sign_in @user
  		flash[:notice] = 'New user created!'
  		redirect_to @user, notice: 'User was successfully created.'
  	else
  		flash[:errors] = @user.errors.full_messages
  		redirect_to '/'
  	end
  end

  def show
  	@user = User.find(session[:user_id])
  end
  #define strong parameters!
  private
  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
    #set the value of the current user, IE use the method below
    self.current_user=(user)
  end
  
  # setter method, set the value of the current user as an instance variable!
  def current_user=(user)
    @current_user = user
  end

  # getter method, returns info of current user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  #if there is a current user, IE someone is logged in, this function returns TRUE!
  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    #resets the current user to nil using the current_user= setter method
    self.current_user = nil
  end

  #this function returns true if the user I pass to the function is equal the current user signed in
  def current_user?(user)
    user == self.current_user 
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Wall Redux</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Wall Redux</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/signup">Register</a></li>
        <li><a href="/signin">Sign In</a></li>
        <!-- <li><a href="#">Wall</a></li> -->
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<div id="main-holder" class="container">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/messages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Wall Redux</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Wall Redux</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/profile/<%= session[:user_id] %>">Profile</a></li>
        <li><a href="/signout">Sign Off</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
<div id="main-holder" class="container">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Wall Redux</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Wall Redux</a>
    </div>
    <% if session[:user_id] %>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="/profile/<%= session[:user_id] %>">Profile</a></li>
          <li><a href="/signout">Sign Off</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    <% else %>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
          <li><a href="/signup">Register</a></li> 
          <li><a href="/signin">Sign in</a></li>
          <!-- <li><a href="#">Wall</a></li> -->
      </ul>
    </div><!--/.nav-collapse -->
    <% end %>
  </div>
</nav>
<div id="main-holder" class="container">
<%= yield %>
</div>
</body>
</html>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/index.html.erb
<div class="col-sm-12">
	<div id="message-form-container">
		<%= bootstrap_form_for(:message, :url => '/messages/') do |f| %>
			<%= f.hidden_field :user_id, value: session[:user_id] %>
			<%= f.text_area :content, hide_label: true, placeholder: "What's on your mind?", rows: 5 %>
			<%= f.submit "Post", class: "btn btn-default btn-lg btn-block" %>
		<% end %>
	</div>
	<div id="messages-container">
		<ul>
			<% @messages.each do |m| %>
				<li>
					<h4><%= m.first_name %> <%= m.last_name %> - <%= m.updated_at %></h4>
					<p><%= m.content %></p>
					<ul class="comment-container">
						<% @comments = Comment.select('comments.*, users.first_name, users.last_name').joins(:user).where(message: Message.find(m.id)) %>
						<% @comments.each do |c| %>
						<li>
							<h4><%= c.first_name %> <%= c.last_name %> - <%= c.updated_at %></h4>
							<p><%= c.content %></p>
						</li>
						<% end %>
						<div class="comment-form-container">
							<%= bootstrap_form_for(:comment, :url => '/comments/') do |f| %>
								<%= f.hidden_field :user_id, value: session[:user_id] %>
								<%= f.hidden_field :message_id, value: m.id %>
								<%= f.text_area :content, hide_label: true, placeholder: "Something to add?", rows: 5 %>
								<%= f.submit "Comment", class: "btn btn-default btn-lg btn-block" %>
							<% end %>
		
						</div>
					</ul>
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<div class="row">
	<div class="col-sm-4 col-sm-offset-4 text-center">
		<h1>The Wall Redux</h1>
		<p>A place for interesting ideas. Come and share your thoughts with the world.</p>
	</div>
</div>
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">
		<% if flash[:errors] %>
			<% flash[:errors].each do |error| %>
				<p class="bg-danger bg-errors"><%= error %></p>
			<% end %>
		<% end %>
		<%= bootstrap_form_for(@user) do |f| %>
		  <%= f.text_field :first_name, hide_label: true, placeholder: "First Name", class: "input-lg" %>
		  <%= f.text_field :last_name, hide_label: true, placeholder: "Last Name", class: "input-lg" %>
		  <%= f.email_field :email, hide_label: true, placeholder: "Email", class: "input-lg" %>
		  <%= f.password_field :password, hide_label: true, placeholder: "Password", class: "input-lg" %>
		  <%= f.password_field :password_confirmation, hide_label: true, placeholder: "Confirm Password", class: "input-lg" %>
		  <%= f.submit "Sign Up", class: "btn btn-primary btn-lg btn-block" %>
		<% end %>

	</div>
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="col-sm-4 col-sm-offset-4">

		<h1>Register</h1>
		<span id="helpBlock" class="help-block">Already have an account? <a href="/signin">Login here</a>.</span>
		<% if flash[:errors] %>
			<% flash[:errors].each do |error| %>
				<p class="bg-danger bg-errors"><%= error %></p>
			<% end %>
		<% end %>
		<%= bootstrap_form_for(@user) do |f| %>
		  <%= f.text_field :first_name, hide_label: true, placeholder: "First Name", class: "input-lg" %>
		  <%= f.text_field :last_name, hide_label: true, placeholder: "Last Name", class: "input-lg" %>
		  <%= f.email_field :email, hide_label: true, placeholder: "Email", class: "input-lg" %>
		  <%= f.password_field :password, hide_label: true, placeholder: "Password", class: "input-lg" %>
		  <%= f.password_field :password_confirmation, hide_label: true, placeholder: "Confirm Password", class: "input-lg" %>
		  <%= f.submit "Sign Up", class: "btn btn-primary btn-lg btn-block" %>
		<% end %>

	</div>
</div>
<!-- 
<div class="col-sm-12">
	<div class="col-sm-7">

		<h1>Register</h1>
		<p>This is where you register!</p>

		<div id="signup-container">
			<% if flash[:errors] %>
				<% flash[:errors].each do |error| %>
					<p><%= error %></p>
				<% end %>
			<% end %>
			<form action='/signup' method="post">
				<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
				<div class="form-group">
					<label for="first_name">First Name</label>
					<input type="text" name="user[first_name]" class="form-control" placeholder="First Name">
				</div>
				<div class="form-group">
					<label for="last_name">Last Name</label>
					<input type="text" name="user[last_name]" class="form-control" placeholder="Last Name">
				</div>
				<div class="form-group">
					<label for="email">Email</label>
					<input type="email" name="user[email]" class="form-control" placeholder="Email">
				</div>
				<div class="form-group">
					<label for="password">Password</label>
					<input type="password" name="user[password]" class="form-control" placeholder="Password">
				</div>
				<div class="form-group">
					<label for="confirm_password">Confirm Password</label>
					<input type="password" name="user[confirm_password]" class="form-control" placeholder="Confirm Password">
				</div>
				<div class="form-group">
				    <button type="submit" class="btn btn-default">Register</button>
				</div>
			</form>
		</div>
	</div>
	<div class="col-sm-4 col-sm-offset-1">

		<h1>Login</h1>
		<p>Welcome back!</p>

		<div id="signin-container">
			<form action='/signin' method="post">
				<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
				<div class="form-group">
					<label for="email">Email</label>
					<input type="email" name="user[email]" class="form-control" placeholder="Email">
				</div>
				<div class="form-group">
					<label for="password" class="control-label">Password</label>
					<input type="password" name="user[password]" class="form-control" placeholder="Password">
				</div>
				<div class="form-group">
			    	<button type="submit" class="btn btn-default">Log in</button>
				</div>
			</form>
		</div>
	</div>
</div> -->

app/views/users/show.html.erb
<h1><%= @user.first_name %> user id: <%= @user.id %></h1>
<%= link_to('log off', signout_path) %>